# .github/workflows/chromatic.yml

name: "Chromatic"

on:
  # allows you to run this workflow manually from the Actions tab
  workflow_call:
  
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Set Chromatic Project Token
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: echo "CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN}" >> $GITHUB_ENV

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
